/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Character {
    id: string;
    bio: string;
    clan: string;
    name: string;
    role: string;
    initials: string;
}
export interface Episode {
    id: EpisodeId;
    status: EpisodeStatus;
    title: string;
    duration: bigint;
    thumbnailUrl?: string;
    videoLink?: string;
    summary: string;
    number: EpisodeNumber;
    releaseDate?: Time;
}
export interface Clan {
    id: string;
    primaryColor: string;
    name: string;
    description: string;
    symbol: string;
}
export type EpisodeNumber = bigint;
export interface NewsEntry {
    id: string;
    title: string;
    body: string;
    date: Time;
    category: NewsCategory;
}
export interface GalleryImage {
    id: string;
    title: string;
    thumbnail: string;
    imageData?: Uint8Array;
    path: string;
    category: GalleryCategory;
    altText: string;
}
export type EpisodeId = string;
export interface UserProfile {
    name: string;
    email: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum EpisodeStatus {
    InProduction = "InProduction",
    Released = "Released",
    ComingSoon = "ComingSoon"
}
export enum GalleryCategory {
    FightScenes = "FightScenes",
    ConceptArt = "ConceptArt",
    CharacterDesigns = "CharacterDesigns"
}
export enum NewsCategory {
    SeasonUpdate = "SeasonUpdate",
    DevLog = "DevLog",
    EpisodeAnnouncement = "EpisodeAnnouncement"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addCharacter(character: Character): Promise<void>;
    addClan(clan: Clan): Promise<void>;
    addEpisode(episode: Episode): Promise<void>;
    addGalleryImage(image: GalleryImage): Promise<void>;
    addNewsEntry(entry: NewsEntry): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    deleteCharacter(id: string): Promise<void>;
    deleteEpisode(id: string): Promise<void>;
    deleteGalleryImage(id: string): Promise<void>;
    deleteNewsEntry(id: string): Promise<void>;
    getAllCharacters(): Promise<Array<Character>>;
    getAllClans(): Promise<Array<Clan>>;
    getAllEpisodes(): Promise<Array<Episode>>;
    getAllGalleryImages(): Promise<Array<GalleryImage>>;
    getAllNewsEntries(): Promise<Array<NewsEntry>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCharacter(id: string): Promise<Character | null>;
    getCharacterCount(): Promise<bigint>;
    getClan(id: string): Promise<Clan | null>;
    getClanCount(): Promise<bigint>;
    getClansByColor(color: string): Promise<Array<Clan>>;
    getEpisode(id: string): Promise<Episode | null>;
    getEpisodeCount(): Promise<bigint>;
    getEpisodesByStatus(status: EpisodeStatus): Promise<Array<Episode>>;
    getGalleryImage(id: string): Promise<GalleryImage | null>;
    getGalleryImageCount(): Promise<bigint>;
    getGalleryImagesByCategory(category: GalleryCategory): Promise<Array<GalleryImage>>;
    getNewsEntriesByCategory(category: NewsCategory): Promise<Array<NewsEntry>>;
    getNewsEntry(id: string): Promise<NewsEntry | null>;
    getNewsEntryCount(): Promise<bigint>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    resetData(): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchCharactersByName(searchTerm: string): Promise<Array<Character>>;
    searchEpisodes(searchTerm: string): Promise<Array<Episode>>;
    updateCharacter(character: Character): Promise<void>;
    updateClan(clan: Clan): Promise<void>;
    updateEpisode(episode: Episode): Promise<void>;
    updateGalleryImage(image: GalleryImage): Promise<void>;
    updateNewsEntry(entry: NewsEntry): Promise<void>;
}
import type { Character as _Character, Clan as _Clan, Episode as _Episode, EpisodeId as _EpisodeId, EpisodeNumber as _EpisodeNumber, EpisodeStatus as _EpisodeStatus, GalleryCategory as _GalleryCategory, GalleryImage as _GalleryImage, NewsCategory as _NewsCategory, NewsEntry as _NewsEntry, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addCharacter(arg0: Character): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCharacter(arg0);
            return result;
        }
    }
    async addClan(arg0: Clan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addClan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClan(arg0);
            return result;
        }
    }
    async addEpisode(arg0: Episode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addEpisode(to_candid_Episode_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addEpisode(to_candid_Episode_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addGalleryImage(arg0: GalleryImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addGalleryImage(to_candid_GalleryImage_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addGalleryImage(to_candid_GalleryImage_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async addNewsEntry(arg0: NewsEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addNewsEntry(to_candid_NewsEntry_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addNewsEntry(to_candid_NewsEntry_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n20(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async deleteCharacter(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCharacter(arg0);
            return result;
        }
    }
    async deleteEpisode(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteEpisode(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteEpisode(arg0);
            return result;
        }
    }
    async deleteGalleryImage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGalleryImage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGalleryImage(arg0);
            return result;
        }
    }
    async deleteNewsEntry(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteNewsEntry(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteNewsEntry(arg0);
            return result;
        }
    }
    async getAllCharacters(): Promise<Array<Character>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCharacters();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCharacters();
            return result;
        }
    }
    async getAllClans(): Promise<Array<Clan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClans();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClans();
            return result;
        }
    }
    async getAllEpisodes(): Promise<Array<Episode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEpisodes();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEpisodes();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllGalleryImages(): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGalleryImages();
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGalleryImages();
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllNewsEntries(): Promise<Array<NewsEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllNewsEntries();
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllNewsEntries();
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacter(arg0: string): Promise<Character | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacter(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacter(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCharacterCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getCharacterCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCharacterCount();
            return result;
        }
    }
    async getClan(arg0: string): Promise<Clan | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClan(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClan(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClanCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getClanCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClanCount();
            return result;
        }
    }
    async getClansByColor(arg0: string): Promise<Array<Clan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClansByColor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClansByColor(arg0);
            return result;
        }
    }
    async getEpisode(arg0: string): Promise<Episode | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisode(arg0);
                return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisode(arg0);
            return from_candid_opt_n45(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEpisodeCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisodeCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisodeCount();
            return result;
        }
    }
    async getEpisodesByStatus(arg0: EpisodeStatus): Promise<Array<Episode>> {
        if (this.processError) {
            try {
                const result = await this.actor.getEpisodesByStatus(to_candid_EpisodeStatus_n10(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEpisodesByStatus(to_candid_EpisodeStatus_n10(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImage(arg0: string): Promise<GalleryImage | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImage(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImage(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGalleryImageCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImageCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImageCount();
            return result;
        }
    }
    async getGalleryImagesByCategory(arg0: GalleryCategory): Promise<Array<GalleryImage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getGalleryImagesByCategory(to_candid_GalleryCategory_n14(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGalleryImagesByCategory(to_candid_GalleryCategory_n14(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsEntriesByCategory(arg0: NewsCategory): Promise<Array<NewsEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsEntriesByCategory(to_candid_NewsCategory_n18(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsEntriesByCategory(to_candid_NewsCategory_n18(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsEntry(arg0: string): Promise<NewsEntry | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsEntry(arg0);
                return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsEntry(arg0);
            return from_candid_opt_n47(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsEntryCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsEntryCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsEntryCount();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async resetData(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.resetData();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.resetData();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchCharactersByName(arg0: string): Promise<Array<Character>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchCharactersByName(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchCharactersByName(arg0);
            return result;
        }
    }
    async searchEpisodes(arg0: string): Promise<Array<Episode>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEpisodes(arg0);
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEpisodes(arg0);
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateCharacter(arg0: Character): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCharacter(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCharacter(arg0);
            return result;
        }
    }
    async updateClan(arg0: Clan): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClan(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClan(arg0);
            return result;
        }
    }
    async updateEpisode(arg0: Episode): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEpisode(to_candid_Episode_n8(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEpisode(to_candid_Episode_n8(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateGalleryImage(arg0: GalleryImage): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGalleryImage(to_candid_GalleryImage_n12(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGalleryImage(to_candid_GalleryImage_n12(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateNewsEntry(arg0: NewsEntry): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateNewsEntry(to_candid_NewsEntry_n16(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateNewsEntry(to_candid_NewsEntry_n16(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_EpisodeStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EpisodeStatus): EpisodeStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_Episode_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Episode): Episode {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_GalleryCategory_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryCategory): GalleryCategory {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_GalleryImage_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GalleryImage): GalleryImage {
    return from_candid_record_n31(_uploadFile, _downloadFile, value);
}
function from_candid_NewsCategory_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsCategory): NewsCategory {
    return from_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function from_candid_NewsEntry_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NewsEntry): NewsEntry {
    return from_candid_record_n37(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [Uint8Array]): Uint8Array | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Character]): Character | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Clan]): Clan | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Episode]): Episode | null {
    return value.length === 0 ? null : from_candid_Episode_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GalleryImage]): GalleryImage | null {
    return value.length === 0 ? null : from_candid_GalleryImage_n30(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_NewsEntry]): NewsEntry | null {
    return value.length === 0 ? null : from_candid_NewsEntry_n36(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _EpisodeId;
    status: _EpisodeStatus;
    title: string;
    duration: bigint;
    thumbnailUrl: [] | [string];
    videoLink: [] | [string];
    summary: string;
    number: _EpisodeNumber;
    releaseDate: [] | [_Time];
}): {
    id: EpisodeId;
    status: EpisodeStatus;
    title: string;
    duration: bigint;
    thumbnailUrl?: string;
    videoLink?: string;
    summary: string;
    number: EpisodeNumber;
    releaseDate?: Time;
} {
    return {
        id: value.id,
        status: from_candid_EpisodeStatus_n25(_uploadFile, _downloadFile, value.status),
        title: value.title,
        duration: value.duration,
        thumbnailUrl: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.thumbnailUrl)),
        videoLink: record_opt_to_undefined(from_candid_opt_n27(_uploadFile, _downloadFile, value.videoLink)),
        summary: value.summary,
        number: value.number,
        releaseDate: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.releaseDate))
    };
}
function from_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    thumbnail: string;
    imageData: [] | [Uint8Array];
    path: string;
    category: _GalleryCategory;
    altText: string;
}): {
    id: string;
    title: string;
    thumbnail: string;
    imageData?: Uint8Array;
    path: string;
    category: GalleryCategory;
    altText: string;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnail: value.thumbnail,
        imageData: record_opt_to_undefined(from_candid_opt_n32(_uploadFile, _downloadFile, value.imageData)),
        path: value.path,
        category: from_candid_GalleryCategory_n33(_uploadFile, _downloadFile, value.category),
        altText: value.altText
    };
}
function from_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    body: string;
    date: _Time;
    category: _NewsCategory;
}): {
    id: string;
    title: string;
    body: string;
    date: Time;
    category: NewsCategory;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        date: value.date,
        category: from_candid_NewsCategory_n38(_uploadFile, _downloadFile, value.category)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    InProduction: null;
} | {
    Released: null;
} | {
    ComingSoon: null;
}): EpisodeStatus {
    return "InProduction" in value ? EpisodeStatus.InProduction : "Released" in value ? EpisodeStatus.Released : "ComingSoon" in value ? EpisodeStatus.ComingSoon : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FightScenes: null;
} | {
    ConceptArt: null;
} | {
    CharacterDesigns: null;
}): GalleryCategory {
    return "FightScenes" in value ? GalleryCategory.FightScenes : "ConceptArt" in value ? GalleryCategory.ConceptArt : "CharacterDesigns" in value ? GalleryCategory.CharacterDesigns : value;
}
function from_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    SeasonUpdate: null;
} | {
    DevLog: null;
} | {
    EpisodeAnnouncement: null;
}): NewsCategory {
    return "SeasonUpdate" in value ? NewsCategory.SeasonUpdate : "DevLog" in value ? NewsCategory.DevLog : "EpisodeAnnouncement" in value ? NewsCategory.EpisodeAnnouncement : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Episode>): Array<Episode> {
    return value.map((x)=>from_candid_Episode_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GalleryImage>): Array<GalleryImage> {
    return value.map((x)=>from_candid_GalleryImage_n30(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_NewsEntry>): Array<NewsEntry> {
    return value.map((x)=>from_candid_NewsEntry_n36(_uploadFile, _downloadFile, x));
}
function to_candid_EpisodeStatus_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EpisodeStatus): _EpisodeStatus {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_Episode_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Episode): _Episode {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_GalleryCategory_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryCategory): _GalleryCategory {
    return to_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function to_candid_GalleryImage_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryImage): _GalleryImage {
    return to_candid_record_n13(_uploadFile, _downloadFile, value);
}
function to_candid_NewsCategory_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): _NewsCategory {
    return to_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function to_candid_NewsEntry_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsEntry): _NewsEntry {
    return to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    thumbnail: string;
    imageData?: Uint8Array;
    path: string;
    category: GalleryCategory;
    altText: string;
}): {
    id: string;
    title: string;
    thumbnail: string;
    imageData: [] | [Uint8Array];
    path: string;
    category: _GalleryCategory;
    altText: string;
} {
    return {
        id: value.id,
        title: value.title,
        thumbnail: value.thumbnail,
        imageData: value.imageData ? candid_some(value.imageData) : candid_none(),
        path: value.path,
        category: to_candid_GalleryCategory_n14(_uploadFile, _downloadFile, value.category),
        altText: value.altText
    };
}
function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    title: string;
    body: string;
    date: Time;
    category: NewsCategory;
}): {
    id: string;
    title: string;
    body: string;
    date: _Time;
    category: _NewsCategory;
} {
    return {
        id: value.id,
        title: value.title,
        body: value.body,
        date: value.date,
        category: to_candid_NewsCategory_n18(_uploadFile, _downloadFile, value.category)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: EpisodeId;
    status: EpisodeStatus;
    title: string;
    duration: bigint;
    thumbnailUrl?: string;
    videoLink?: string;
    summary: string;
    number: EpisodeNumber;
    releaseDate?: Time;
}): {
    id: _EpisodeId;
    status: _EpisodeStatus;
    title: string;
    duration: bigint;
    thumbnailUrl: [] | [string];
    videoLink: [] | [string];
    summary: string;
    number: _EpisodeNumber;
    releaseDate: [] | [_Time];
} {
    return {
        id: value.id,
        status: to_candid_EpisodeStatus_n10(_uploadFile, _downloadFile, value.status),
        title: value.title,
        duration: value.duration,
        thumbnailUrl: value.thumbnailUrl ? candid_some(value.thumbnailUrl) : candid_none(),
        videoLink: value.videoLink ? candid_some(value.videoLink) : candid_none(),
        summary: value.summary,
        number: value.number,
        releaseDate: value.releaseDate ? candid_some(value.releaseDate) : candid_none()
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EpisodeStatus): {
    InProduction: null;
} | {
    Released: null;
} | {
    ComingSoon: null;
} {
    return value == EpisodeStatus.InProduction ? {
        InProduction: null
    } : value == EpisodeStatus.Released ? {
        Released: null
    } : value == EpisodeStatus.ComingSoon ? {
        ComingSoon: null
    } : value;
}
function to_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GalleryCategory): {
    FightScenes: null;
} | {
    ConceptArt: null;
} | {
    CharacterDesigns: null;
} {
    return value == GalleryCategory.FightScenes ? {
        FightScenes: null
    } : value == GalleryCategory.ConceptArt ? {
        ConceptArt: null
    } : value == GalleryCategory.CharacterDesigns ? {
        CharacterDesigns: null
    } : value;
}
function to_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewsCategory): {
    SeasonUpdate: null;
} | {
    DevLog: null;
} | {
    EpisodeAnnouncement: null;
} {
    return value == NewsCategory.SeasonUpdate ? {
        SeasonUpdate: null
    } : value == NewsCategory.DevLog ? {
        DevLog: null
    } : value == NewsCategory.EpisodeAnnouncement ? {
        EpisodeAnnouncement: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
