/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Character = IDL.Record({
  'id' : IDL.Text,
  'bio' : IDL.Text,
  'clan' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'initials' : IDL.Text,
});
export const Clan = IDL.Record({
  'id' : IDL.Text,
  'primaryColor' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'symbol' : IDL.Text,
});
export const EpisodeId = IDL.Text;
export const EpisodeStatus = IDL.Variant({
  'InProduction' : IDL.Null,
  'Released' : IDL.Null,
  'ComingSoon' : IDL.Null,
});
export const EpisodeNumber = IDL.Nat;
export const Time = IDL.Int;
export const Episode = IDL.Record({
  'id' : EpisodeId,
  'status' : EpisodeStatus,
  'title' : IDL.Text,
  'duration' : IDL.Nat,
  'thumbnailUrl' : IDL.Opt(IDL.Text),
  'videoLink' : IDL.Opt(IDL.Text),
  'summary' : IDL.Text,
  'number' : EpisodeNumber,
  'releaseDate' : IDL.Opt(Time),
});
export const GalleryCategory = IDL.Variant({
  'FightScenes' : IDL.Null,
  'ConceptArt' : IDL.Null,
  'CharacterDesigns' : IDL.Null,
});
export const GalleryImage = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'thumbnail' : IDL.Text,
  'imageData' : IDL.Opt(IDL.Vec(IDL.Nat8)),
  'path' : IDL.Text,
  'category' : GalleryCategory,
  'altText' : IDL.Text,
});
export const NewsCategory = IDL.Variant({
  'SeasonUpdate' : IDL.Null,
  'DevLog' : IDL.Null,
  'EpisodeAnnouncement' : IDL.Null,
});
export const NewsEntry = IDL.Record({
  'id' : IDL.Text,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'date' : Time,
  'category' : NewsCategory,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCharacter' : IDL.Func([Character], [], []),
  'addClan' : IDL.Func([Clan], [], []),
  'addEpisode' : IDL.Func([Episode], [], []),
  'addGalleryImage' : IDL.Func([GalleryImage], [], []),
  'addNewsEntry' : IDL.Func([NewsEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCharacter' : IDL.Func([IDL.Text], [], []),
  'deleteEpisode' : IDL.Func([IDL.Text], [], []),
  'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
  'deleteNewsEntry' : IDL.Func([IDL.Text], [], []),
  'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
  'getAllClans' : IDL.Func([], [IDL.Vec(Clan)], ['query']),
  'getAllEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
  'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
  'getAllNewsEntries' : IDL.Func([], [IDL.Vec(NewsEntry)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCharacter' : IDL.Func([IDL.Text], [IDL.Opt(Character)], ['query']),
  'getCharacterCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getClan' : IDL.Func([IDL.Text], [IDL.Opt(Clan)], ['query']),
  'getClanCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getClansByColor' : IDL.Func([IDL.Text], [IDL.Vec(Clan)], ['query']),
  'getEpisode' : IDL.Func([IDL.Text], [IDL.Opt(Episode)], ['query']),
  'getEpisodeCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getEpisodesByStatus' : IDL.Func(
      [EpisodeStatus],
      [IDL.Vec(Episode)],
      ['query'],
    ),
  'getGalleryImage' : IDL.Func([IDL.Text], [IDL.Opt(GalleryImage)], ['query']),
  'getGalleryImageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getGalleryImagesByCategory' : IDL.Func(
      [GalleryCategory],
      [IDL.Vec(GalleryImage)],
      ['query'],
    ),
  'getNewsEntriesByCategory' : IDL.Func(
      [NewsCategory],
      [IDL.Vec(NewsEntry)],
      ['query'],
    ),
  'getNewsEntry' : IDL.Func([IDL.Text], [IDL.Opt(NewsEntry)], ['query']),
  'getNewsEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'resetData' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchCharactersByName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Character)],
      ['query'],
    ),
  'searchEpisodes' : IDL.Func([IDL.Text], [IDL.Vec(Episode)], ['query']),
  'updateCharacter' : IDL.Func([Character], [], []),
  'updateClan' : IDL.Func([Clan], [], []),
  'updateEpisode' : IDL.Func([Episode], [], []),
  'updateGalleryImage' : IDL.Func([GalleryImage], [], []),
  'updateNewsEntry' : IDL.Func([NewsEntry], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Character = IDL.Record({
    'id' : IDL.Text,
    'bio' : IDL.Text,
    'clan' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'initials' : IDL.Text,
  });
  const Clan = IDL.Record({
    'id' : IDL.Text,
    'primaryColor' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'symbol' : IDL.Text,
  });
  const EpisodeId = IDL.Text;
  const EpisodeStatus = IDL.Variant({
    'InProduction' : IDL.Null,
    'Released' : IDL.Null,
    'ComingSoon' : IDL.Null,
  });
  const EpisodeNumber = IDL.Nat;
  const Time = IDL.Int;
  const Episode = IDL.Record({
    'id' : EpisodeId,
    'status' : EpisodeStatus,
    'title' : IDL.Text,
    'duration' : IDL.Nat,
    'thumbnailUrl' : IDL.Opt(IDL.Text),
    'videoLink' : IDL.Opt(IDL.Text),
    'summary' : IDL.Text,
    'number' : EpisodeNumber,
    'releaseDate' : IDL.Opt(Time),
  });
  const GalleryCategory = IDL.Variant({
    'FightScenes' : IDL.Null,
    'ConceptArt' : IDL.Null,
    'CharacterDesigns' : IDL.Null,
  });
  const GalleryImage = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'thumbnail' : IDL.Text,
    'imageData' : IDL.Opt(IDL.Vec(IDL.Nat8)),
    'path' : IDL.Text,
    'category' : GalleryCategory,
    'altText' : IDL.Text,
  });
  const NewsCategory = IDL.Variant({
    'SeasonUpdate' : IDL.Null,
    'DevLog' : IDL.Null,
    'EpisodeAnnouncement' : IDL.Null,
  });
  const NewsEntry = IDL.Record({
    'id' : IDL.Text,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'date' : Time,
    'category' : NewsCategory,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCharacter' : IDL.Func([Character], [], []),
    'addClan' : IDL.Func([Clan], [], []),
    'addEpisode' : IDL.Func([Episode], [], []),
    'addGalleryImage' : IDL.Func([GalleryImage], [], []),
    'addNewsEntry' : IDL.Func([NewsEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCharacter' : IDL.Func([IDL.Text], [], []),
    'deleteEpisode' : IDL.Func([IDL.Text], [], []),
    'deleteGalleryImage' : IDL.Func([IDL.Text], [], []),
    'deleteNewsEntry' : IDL.Func([IDL.Text], [], []),
    'getAllCharacters' : IDL.Func([], [IDL.Vec(Character)], ['query']),
    'getAllClans' : IDL.Func([], [IDL.Vec(Clan)], ['query']),
    'getAllEpisodes' : IDL.Func([], [IDL.Vec(Episode)], ['query']),
    'getAllGalleryImages' : IDL.Func([], [IDL.Vec(GalleryImage)], ['query']),
    'getAllNewsEntries' : IDL.Func([], [IDL.Vec(NewsEntry)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCharacter' : IDL.Func([IDL.Text], [IDL.Opt(Character)], ['query']),
    'getCharacterCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getClan' : IDL.Func([IDL.Text], [IDL.Opt(Clan)], ['query']),
    'getClanCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getClansByColor' : IDL.Func([IDL.Text], [IDL.Vec(Clan)], ['query']),
    'getEpisode' : IDL.Func([IDL.Text], [IDL.Opt(Episode)], ['query']),
    'getEpisodeCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getEpisodesByStatus' : IDL.Func(
        [EpisodeStatus],
        [IDL.Vec(Episode)],
        ['query'],
      ),
    'getGalleryImage' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(GalleryImage)],
        ['query'],
      ),
    'getGalleryImageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getGalleryImagesByCategory' : IDL.Func(
        [GalleryCategory],
        [IDL.Vec(GalleryImage)],
        ['query'],
      ),
    'getNewsEntriesByCategory' : IDL.Func(
        [NewsCategory],
        [IDL.Vec(NewsEntry)],
        ['query'],
      ),
    'getNewsEntry' : IDL.Func([IDL.Text], [IDL.Opt(NewsEntry)], ['query']),
    'getNewsEntryCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'resetData' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchCharactersByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Character)],
        ['query'],
      ),
    'searchEpisodes' : IDL.Func([IDL.Text], [IDL.Vec(Episode)], ['query']),
    'updateCharacter' : IDL.Func([Character], [], []),
    'updateClan' : IDL.Func([Clan], [], []),
    'updateEpisode' : IDL.Func([Episode], [], []),
    'updateGalleryImage' : IDL.Func([GalleryImage], [], []),
    'updateNewsEntry' : IDL.Func([NewsEntry], [], []),
  });
};

export const init = ({ IDL }) => { return []; };