/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Character {
  'id' : string,
  'bio' : string,
  'clan' : string,
  'name' : string,
  'role' : string,
  'initials' : string,
}
export interface Clan {
  'id' : string,
  'primaryColor' : string,
  'name' : string,
  'description' : string,
  'symbol' : string,
}
export interface Episode {
  'id' : EpisodeId,
  'status' : EpisodeStatus,
  'title' : string,
  'duration' : bigint,
  'thumbnailUrl' : [] | [string],
  'videoLink' : [] | [string],
  'summary' : string,
  'number' : EpisodeNumber,
  'releaseDate' : [] | [Time],
}
export type EpisodeId = string;
export type EpisodeNumber = bigint;
export type EpisodeStatus = { 'InProduction' : null } |
  { 'Released' : null } |
  { 'ComingSoon' : null };
export type GalleryCategory = { 'FightScenes' : null } |
  { 'ConceptArt' : null } |
  { 'CharacterDesigns' : null };
export interface GalleryImage {
  'id' : string,
  'title' : string,
  'thumbnail' : string,
  'imageData' : [] | [Uint8Array],
  'path' : string,
  'category' : GalleryCategory,
  'altText' : string,
}
export type NewsCategory = { 'SeasonUpdate' : null } |
  { 'DevLog' : null } |
  { 'EpisodeAnnouncement' : null };
export interface NewsEntry {
  'id' : string,
  'title' : string,
  'body' : string,
  'date' : Time,
  'category' : NewsCategory,
}
export type Time = bigint;
export interface UserProfileView {
  'matchedClanId' : [] | [string],
  'username' : string,
  'matchedCharacterId' : [] | [string],
  'unlockedBadges' : Array<string>,
  'avatarUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCharacter' : ActorMethod<[Character], undefined>,
  'addClan' : ActorMethod<[Clan], undefined>,
  'addEpisode' : ActorMethod<[Episode], undefined>,
  'addGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'addNewsEntry' : ActorMethod<[NewsEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCharacter' : ActorMethod<[string], undefined>,
  'deleteEpisode' : ActorMethod<[string], undefined>,
  'deleteGalleryImage' : ActorMethod<[string], undefined>,
  'deleteNewsEntry' : ActorMethod<[string], undefined>,
  'getAllCharacters' : ActorMethod<[], Array<Character>>,
  'getAllClans' : ActorMethod<[], Array<Clan>>,
  'getAllEpisodes' : ActorMethod<[], Array<Episode>>,
  'getAllGalleryImages' : ActorMethod<[], Array<GalleryImage>>,
  'getAllNewsEntries' : ActorMethod<[], Array<NewsEntry>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfileView]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCharacter' : ActorMethod<[string], [] | [Character]>,
  'getCharacterCount' : ActorMethod<[], bigint>,
  'getClan' : ActorMethod<[string], [] | [Clan]>,
  'getClanCount' : ActorMethod<[], bigint>,
  'getClansByColor' : ActorMethod<[string], Array<Clan>>,
  'getEpisode' : ActorMethod<[string], [] | [Episode]>,
  'getEpisodeCount' : ActorMethod<[], bigint>,
  'getEpisodesByStatus' : ActorMethod<[EpisodeStatus], Array<Episode>>,
  'getGalleryImage' : ActorMethod<[string], [] | [GalleryImage]>,
  'getGalleryImageCount' : ActorMethod<[], bigint>,
  'getGalleryImagesByCategory' : ActorMethod<
    [GalleryCategory],
    Array<GalleryImage>
  >,
  'getNewsEntriesByCategory' : ActorMethod<[NewsCategory], Array<NewsEntry>>,
  'getNewsEntry' : ActorMethod<[string], [] | [NewsEntry]>,
  'getNewsEntryCount' : ActorMethod<[], bigint>,
  'getUnlockedBadges' : ActorMethod<[], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfileView]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'resetData' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfileView], undefined>,
  'searchCharactersByName' : ActorMethod<[string], Array<Character>>,
  'searchEpisodes' : ActorMethod<[string], Array<Episode>>,
  'unlockBadge' : ActorMethod<[string], undefined>,
  'updateCharacter' : ActorMethod<[Character], undefined>,
  'updateClan' : ActorMethod<[Clan], undefined>,
  'updateEpisode' : ActorMethod<[Episode], undefined>,
  'updateGalleryImage' : ActorMethod<[GalleryImage], undefined>,
  'updateNewsEntry' : ActorMethod<[NewsEntry], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];